# -*- coding: utf-8 -*-
"""Copy of week1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lYgiZg88IAgE5dQoKom70YDv5ky_GAN
"""



import pandas as pd
import numpy as np

df=pd.read_csv('/content/sample_data/california_housing_test.csv')
df

df.head()

df.tail()

df.describe()

df.size

df.shape

df.info()

# prompt: [1,5,7,2,65,8,3,7,3,7,2

my_list = [1, 5, 7, 2, 65, 8, 3, 7, 3, 7, 2]